twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_5_layout.html.twig
    globals:
        projectDir: '%kernel.project_dir%'
        translator: '@app.translator'
        settings: '@app.settings'
        cookie: '@app.cookie'
        editorTitle: 'Czechsaber e'

when@test:
    twig:
        strict_variables: true